# Generated by Django 5.2.1 on 2025-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidat",
            name="odeme_yontemi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nakit", "Nakit"),
                    ("kredi_karti", "Kredi Kartı"),
                    ("banka_havalesi", "Banka Havalesi/EFT"),
                    ("diger", "Diğer"),
                ],
                default="diger",
                max_length=20,
                null=True,
                verbose_name="Ödeme Yöntemi",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="banka_adi",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Banka Adı"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="banka_hesap_adi",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Banka Hesap Adı"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="duyurular",
            field=models.TextField(blank=True, verbose_name="Duyurular"),
        ),
        migrations.AddField(
            model_name="site",
            name="gecikme_faizi_orani",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Örn: 0.0050 (yani %0.5). Günlük uygulanacak faiz oranı.",
                max_digits=5,
                null=True,
                verbose_name="Gecikme Faizi Oranı (Günlük)",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AddField(
            model_name="site",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_logolari/",
                verbose_name="Site Logosu",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="otomatik_mail_aktif",
            field=models.BooleanField(
                default=False, verbose_name="Otomatik Mail Gönderimi Aktif mi?"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="site_kurallari",
            field=models.TextField(blank=True, verbose_name="Site Kuralları"),
        ),
        migrations.AddField(
            model_name="site",
            name="son_odeme_gunu_oncesi_hatirlatma",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Aidat son ödeme gününden kaç gün önce hatırlatma maili gönderilsin? (0 pasif yapar)",
                verbose_name="Hatırlatma Günü Sayısı",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="yonetici_adi",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Yönetici Adı Soyadı"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="yonetici_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Yönetici E-postası"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="yonetici_telefonu",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Yönetici Telefonu"
            ),
        ),
    ]
