# Generated by Django 5.2.1 on 2025-05-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0002_aidat_odeme_yontemi_site_banka_adi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kullanici",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
    ]
