# Generated by Django 5.2.1 on 2025-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0003_alter_kullanici_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="daire",
            name="aciklama",
            field=models.TextField(
                blank=True, null=True, verbose_name="Daire Açıklaması"
            ),
        ),
        migrations.AddField(
            model_name="daire",
            name="daire_tipi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1+1", "1+1"),
                    ("2+1", "2+1"),
                    ("3+1", "3+1"),
                    ("4+1", "4+1"),
                    ("5+1", "5+1"),
                    ("dublex", "Dublex"),
                    ("isyeri", "İş Yeri"),
                    ("diger", "Diğer"),
                ],
                default="diger",
                max_length=20,
                null=True,
                verbose_name="Daire Tipi",
            ),
        ),
        migrations.AddField(
            model_name="daire",
            name="is_dolu",
            field=models.BooleanField(default=True, verbose_name="Daire Dolu mu?"),
        ),
        migrations.AddField(
            model_name="daire",
            name="m2_brut",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Brüt Metrekare",
            ),
        ),
        migrations.AddField(
            model_name="daire",
            name="m2_net",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Net Metrekare",
            ),
        ),
    ]
