# Generated by Django 5.2.1 on 2025-05-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0004_daire_aciklama_daire_daire_tipi_daire_is_dolu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aidat",
            name="odeme_yontemi",
        ),
    ]
