# Generated by Django 5.2.1 on 2025-05-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0007_update_usernames"),
    ]

    operations = [
        migrations.AddField(
            model_name="blok",
            name="aciklama",
            field=models.TextField(
                blank=True,
                help_text="Blok hakkında ek bilgiler",
                null=True,
                verbose_name="Blok Açıklaması",
            ),
        ),
        migrations.AddField(
            model_name="blok",
            name="aidat_miktari",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bu blok için özel aidat miktarı. Boş bırakılırsa site genel aidat miktarı kullanılır.",
                max_digits=10,
                null=True,
                verbose_name="Blok Aidat Miktarı",
            ),
        ),
    ]
