# Generated by Django 5.2.1 on 2025-05-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yonetim", "0008_add_blok_aidat_miktari"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="banka_adi",
        ),
        migrations.RemoveField(
            model_name="site",
            name="banka_hesap_adi",
        ),
        migrations.RemoveField(
            model_name="site",
            name="iban",
        ),
        migrations.RemoveField(
            model_name="site",
            name="yonetici_telefonu",
        ),
    ]
